var matcher = require("./matcher");
var wordyWords = [
  'abwesend sein',
  'Abwesenheit',
  'aggregieren',
  'akquirieren',
  'akzentuieren',
  'alle von',
  'aller Wahrscheinlichkeit nach',
  'alles und jeder',
  'Als Alternative',
  'als Mittel',
  'angrenzend',
  'antizipieren',
  'anwendbar',
  'äquivalent',
  'Art von',
  'Assistenz',
  'Aufgrund der Tatsache',
  'aufwenden',
  'aufzählen',
  'autorisieren',
  'autorisiert',
  'beauftragen',
  'bemühen',
  'bereits bestehend',
  'betreffend',
  'bezüglich',
  'darlegen',
  'demonstrieren',
  'der Tatsache geschuldet',
  'designieren',
  'Dotierung',
  'ein bestimmtes',
  'ein spezifisches',
  'einbüßen',
  'eine Anzahl von',
  'eine Art',
  'einfach gesagt',
  'Einzelheiten',
  'eliminieren',
  'enumerieren',
  'erbitten',
  'erfolgreich absolvieren',
  'erhellen',
  'erlangen',
  'ermitteln',
  'ersichtlich',
  'es hat den Anschein',
  'es scheint',
  'essentiell',
  'evaluieren',
  'Evidenz',
  'exklusiv',
  'falls und wenn',
  'feststellen',
  'finalisieren',
  'flankieren',
  'folglich',
  'formulieren',
  'fortgehen',
  'für alle Absichten und Zwecke',
  'Geübtheit',
  'gewähren',
  'gewährt',
  'gleichwertig',
  'Größenordnung',
  'größtenteils',
  'hauptsächlich',
  'hinlänglich',
  'hinreichend',
  'im Bezug auf',
  'im Fall von',
  'im Großen und Ganzen',
  'in Anbetracht der Tatsache',
  'in bestimmten Fällen',
  'in bestimmten Situationen',
  'in Bezug auf',
  'in Bezug auf',
  'In der nahen Zukunft',
  'in einigen Fällen',
  'in einigen Situationen',
  'in Hinsicht auf',
  'in lieu',
  'In naher Zukunft',
  'in Übereinstimmung mit',
  'in unmittelbarer Nähe',
  'in vielen Fällen',
  'Inanspruchnahme',
  'indes',
  'Indiz',
  'indizieren',
  'initiieren',
  'inter alia',
  'konsolidieren',
  'konstituieren',
  'konsultieren',
  'lindern',
  'mehrere',
  'meiner Meinung nach',
  'Methodik',
  'modifizieren',
  'nachfolgend',
  'negativ betreffen',
  'nicht oft',
  'nicht selten',
  'nicht unwahrscheinlich',
  'nicht viele',
  'nichtsdestotrotz',
  'Null und nichtig',
  'Nutzbarmachung',
  'objektiv',
  'obliegende',
  'offenbar',
  'offensichtlich',
  'partizipieren',
  'recht und billig',
  'Renumeration',
  'Residenz',
  'residieren',
  'soeben erwähnt',
  'sollten Sie wünschen',
  'statthaft',
  'substantiell',
  'tatsächlich',
  'tendenziell',
  'terminieren',
  'toll',
  'transpirieren',
  'Tüchtigkeit',
  'tunlich',
  'übermitteln',
  'überspannen',
  'unabänderlich',
  'unbestimmt',
  'unter Berücksichtigung',
  'unter der Voraussetzung',
  'unter Überschreitung von',
  'Vergleichbar mit',
  'verlagern',
  'verpflichten',
  'verschaffen',
  'verstummen',
  'viele verschiedene',
  'vollbringen',
  'vorantreiben',
  'Vorteil daraus ziehen',
  'vorteilhaft',
  'was ich sagen wollte',
  'was mich anbelangt',
  'was mich betrifft',
  'wie auch immer',
  'zahlreich',
  'zeitnah',
  'zu dieser Zeit',
  'zu Nutze machen',
  'zuallererst',
  'zum heutigen Zeitpunkt',
  'zum jetzigen Zeitpunkt',
  'zunutze machen',
  'zurechenbar',
  'zurückbehalten',
  'zurückverweisen',
];

var wordyRegex = new RegExp('\\b(' + wordyWords.join('|') + ')\\b', 'gi');

module.exports = function(text) {
  return matcher(wordyRegex, text, "wordy");
};
